### PR TITLE
Added Heap Sort 

### PR DESCRIPTION
**Pull request by thejaswin123**
## Related Issue 

- Info about the related issue 

- [x] DevIncept Participant 
- [x] Contributor

Closes: #12 

### Describe the changes you've made
Added program code in Python for Heap Sort algorithm to sort list of numbers given.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Code is run multiple times with different inputs and test cases and output is verified.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
README needs to be more elaborate. Follow the template for README. The project file should be as "heap_sort.py"
Also the image link you added is user-images content, instead it should be the file path of image present in this repo.

Kindly do these changes. @thejaswin123

**Comment by thejaswin123** [comment]
Changes are made as said @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Welcome to repo officially. Congrats on your first PR. It was a good start. ✨🎉@thejaswin123

**Comment by prathimacode-hub** [comment]
Kindly fill the form with your PR link. You have 1 PR merged in this project. Your response hasn't turned up yet. Form is available in slack project channel. @thejaswin123

**Comment by thejaswin123** [comment]
> Kindly fill the form with your PR link. You have 1 PR merged in this project. Your response hasn't turned up yet. Form is available in slack project channel. @thejaswin123

Filled the form, kindly please check.

**Comment by prathimacode-hub** [comment]
You have to fill the form again, form is updated. So kindly redo it again. That's the reason I'm addressing you. Updated Form is provided in slack channel. @thejaswin123

**Comment by thejaswin123** [comment]
> You have to fill the form again, form is updated. So kindly redo it again. That's the reason I'm addressing you. Updated Form is provided in slack channel. @thejaswin123

I filled the Form again and can u please check again.

**Pull request merged**
