### PR TITLE
Transposition Cipher

### PR DESCRIPTION
**Pull request by RC2208**
## Related Issue 

- Info about the related issue 

- [x] DevIncept Participant 
- [ ] Contributor

Closes: #42 

### Describe the changes you've made

Added code for encryption and decryption of text using transposition cipher.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manually run and tested

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Check it here with the [README template](https://github.com/SamarthMR/AI-ML-for-Newborn-Babies-in-Healthcare/blob/main/.github/README_TEMPLATE.md). Check if you had added up everything or not, you will know the changes yourself.
And also the image links you had added in "README.md" file are of user-images content instead it should be the file path of the images present in this repo.

Kindly address these changes. @RC2208

**Review by prathimacode-hub — APPROVED** [review]
Yayy, your PR is approved. Congrats on your first PR. Great start. Keep it up. ✨🎉👏@RC2208

**Comment by RC2208** [comment]
I have done the changes requested.

**Review by prathimacode-hub — APPROVED** [review]
Welcome to repo. Congrats on your PR. It's approved. Yay. Well done. Great start. ✨🎉👏@RC2208

**Comment by RC2208** [comment]
Thank you!

**Pull request merged**
