### PR TITLE
Palindrome Check with Recursion

### PR DESCRIPTION
**Pull request by pushpit-J19**
## Related Issue 

- Info about the related issue 

- [x] DevIncept Participant 
- [ ] Contributor

Closes: #45 

### Describe the changes you've made

Added the code for checking if a given string is a palindrome or not using recursion based on case sensitive or insensitive comparisons. Added readme files and the outputs

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manually run and tested

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The project file should be as "palindrome_check.py"
Add purpose, workflow of the project and your name at the end of the file.

@pushpit-J19

**Comment by pushpit-J19** [comment]
The desired changes have been done

**Review by prathimacode-hub — APPROVED** [review]
Welcome to repo officially. Wonderful start. PR approved. Congrats on your first PR. Yayy. Get going. 🎉👏✨@pushpit-J19

**Comment by pushpit-J19** [comment]
Thank you

**Pull request merged**
