### PR TITLE
Added Face Detection Algorithm using Haar Cascade

### PR DESCRIPTION
**Pull request by Lashuk1729**
## Related Issue 

- Info about the related issue 

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

Closes: #182 that will be closed through this PR

### Describe the changes you've made
- I added the program for _'Face detection using Haar cascades'_ to detect the faces using the OpenCV Library.

## Type of change
- [x] New feature: Added the algorithm for Face Detection using Haar Cascade
- [x] My code follows the code style of this project.

## How Has This Been Tested?

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly add PR template along with issue number. @Lashuk1729

**Comment by Lashuk1729** [comment]
@prathimacode-hub Thanks a lot for assigning this task to me, please do let me know if anything else needs to be added to the code.

**Comment by prathimacode-hub** [comment]
Kindly add your PR template along with issue number in your PR comment using edit option. I can check once it's done. @Lashuk1729

**Comment by prathimacode-hub** [comment]
Have you done the changes? @Lashuk1729

**Comment by Lashuk1729** [comment]
Yes @prathimacode-hub, I have changed the README based on the template, added the requirement.txt file and added all the images in the image folder.
I hope the PR is good.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. 👏🎉@Lashuk1729

**Pull request merged**
