### PR TITLE
Singly Linked List (#31)

### PR DESCRIPTION
**Pull request by nknantha**
## Related Issue 

- Info about the related issue 

- [x] **DevIncept Participant**
- [ ] ~~Contributor~~

Closes: #31 will be closed through this PR

### Describe the changes you've made
Added Singly Linked List in Python

Implemented Singly Linked List using nodes. Additionally added useful methods like in Python's built-in List(Data Structure).

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Program is test on Python's IDLE and Python Console.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Folow the project structure given. Many files missing. @nknantha

**Comment by nknantha** [comment]
Changes made as per Project Guidelines.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Add 2-3 sample test cases in your README.md instead of saying to run the project
And also in the project file, add appropriate comments in the code to get good understanding of the project. 
At the starting of the project file after you provided a introduction to the script, add a description about singly linked list and also demonstrate it using 2-3 test cases at the end of the project file using comments.
At the end of the README.md file add your full name.

Kindly do these changes. @nknantha

**Review by prathimacode-hub — APPROVED** [review]
Congrats on your first PR. Welcome to repo officially. Yayy. Great start. ✨🎉👏@nknantha

**Pull request merged**
