### PR TITLE
Shell Sort added

### PR DESCRIPTION
**Pull request by neha030**
**Related Issue
Info about the related issue**
I have added the python program for shell sort algorithm

✅ DevIncept Participant

Contributor

Closes: #118 

**Describe the changes you've made**
**Type of change**
Created separate files to and implemented the shell sort algorithm

**What sort of change have you made:**
I have added a new feature i.e the program for Shell Sort Algorithm.

**How Has This Been Tested?**
Describe how have you verified the changes made
The programs was run on VS Code multiple time and checked for issues and error.

**Checklist:**
✅ My code follows the guidelines of this project.
✅ I have performed a self-review of my own code.
✅ I have commented my code, particularly whereever it was hard to understand.
✅ I have made corresponding changes to the documentation.
✅ My changes generate no new warnings.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Your PR has conflicting files due to which I am unable to check on your PR. Kindly correct it from your end.  @neha030

**Comment by neha030** [comment]
I think it's resolved now @prathimacode-hub 
Please review

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
In project file, add a description about shell sort at start of the project file.
Also add the test cases you had removed in README.md

Kindly do these changes. @neha030

**Review by prathimacode-hub — APPROVED** [review]
Awesome work. Great going. PR approved. 🙌🤩@neha030

**Pull request merged**
