### PR TITLE
Digit Recognizer #135

### PR DESCRIPTION
**Pull request by anubhav201241**
#135 

- Info about the related issue 
Digit Recognizer using Knn Algorithm

- [x] DevIncept Participant 
- [ ] Contributor

Closes: #135 
### Describe the changes you've made
Created a Python file and add the Digit Recognizer code in it using Neural Network's algorithm KNN

Give a clear description what modifications you have made

Changes the Digitrecogn.py file and add the train and test models in the folder 

## How Has This Been Tested?

Describe how have you verified the changes made
I have tested it in the Collab notebook and it is working fine 

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.Issue no: #135 

Created the PR for Digit Recognizer which recognize Digits using Knn algorithm 

@prathimacode-hub Kindly Review it and Merge it :)

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly follow the PR template given and add up the details of project along with issue number. You can change it up here itself using edit option. @anubhav201241

**Comment by anubhav201241** [comment]
@prathimacode-hub I have made the PR

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
You can't add up the project separately instead you should add your project in relevant category given.
Also follow the project structure given along with the README template. This is not the right format to do so. 
As well the project file should be in .ipynb format. First go through the README file of this project. You would find all the details needed to make a successful PR.

Kindly do the changes. @anubhav201241

**Comment by prathimacode-hub** [comment]
What about the changes that needs to be done here? @anubhav201241

**Comment by anubhav201241** [comment]
@prathimacode-hub added .pynb file can you drag digit recognizer folder in that folder in which you want to keep it because that's only the work that is left so can you drag that

**Comment by prathimacode-hub** [comment]
This is still not in project structure. For your PR in other repo also I said same. If i drag it, it won't show your name as contributor but it would show up my name as updated. What should I do now? I have to send the scores. Its already late. And morever your PR won't count unless you don't fill up the PR form as well. When you would do all the changes? When you would fill up the form? When shall i submit the scores? I am already late in doing so in hope that you would correct it and finish off. Don't you think I'm being extra lenient with you. @anubhav201241

**Pull request closed without merging**
