### PR TITLE
Sudoku Solver #18 added

### PR DESCRIPTION
**Pull request by dhruv-varshney**
Related Issue
Add Binary Search.

 DevIncept Participant

 Contributor

Closes: #18 

Describe the changes you've made

- [x] I have added Sudoku Solver using Backtracking

Type of change
What sort of change have you made:

 

- [ ] Bug fix (non-breaking change which fixes an issue)

 

- [x] New feature (non-breaking change which adds functionality)

 

- [ ] Code style update (formatting, local variables)

 

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  This change requires a documentation update

 
How Has This Been Tested?
Describe how have you verified the changes made
I ran the program in my ubuntu operating system and ide is the text editor of ubuntu

Checklist:
 

- [x] My code follows the guidelines of this project.

 

- [x] I have performed a self-review of my own code.

 

- [x] I have commented on my code, particularly wherever it was hard to understand.

 

- [x] I have made corresponding changes to the documentation.

 

- [x] My changes generate no new warnings.

### CODE REVIEW

**Comment by ankitapuri** [comment]
> Related Issue
> Add Binary Search.
> 
> DevIncept Participant
> 
> Contributor
> 
> Closes: #18
> 
> Describe the changes you've made
> 
> * [x]  I have added Sudoku Solver using Backtracking
> 
> Type of change
> What sort of change have you made:
> 
> * [ ]  Bug fix (non-breaking change which fixes an issue)
> * [x]  New feature (non-breaking change which adds functionality)
> * [ ]  Code style update (formatting, local variables)
> * [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
> * [ ]   This change requires a documentation update
> 
> How Has This Been Tested?
> Describe how have you verified the changes made
> I ran the program in my ubuntu operating system and ide is the text editor of ubuntu
> 
> Checklist:
> 
> * [x]  My code follows the guidelines of this project.
> * [x]  I have performed a self-review of my own code.
> * [x]  I have commented on my code, particularly wherever it was hard to understand.
> * [x]  I have made corresponding changes to the documentation.
> * [x]  My changes generate no new warnings.
> * [x]  I have added test cases that prove my fix is effective or that my feature works.

Just tick mark the boxes which suits your pull request in order to follow the template and so that we can review accordingly

**Comment by dhruv-varshney** [comment]
> > Related Issue
> > Add Binary Search.
> > DevIncept Participant
> > Contributor
> > Closes: #18
> > Describe the changes you've made
> > 
> > * [x]   I have added Sudoku Solver using Backtracking
> > 
> > Type of change
> > What sort of change have you made:
> > 
> > * [ ]   Bug fix (non-breaking change which fixes an issue)
> > * [x]   New feature (non-breaking change which adds functionality)
> > * [ ]   Code style update (formatting, local variables)
> > * [ ]   Breaking change (fix or feature that would cause existing functionality to not work as expected)
> > * [ ]    This change requires a documentation update
> > 
> > How Has This Been Tested?
> > Describe how have you verified the changes made
> > I ran the program in my ubuntu operating system and ide is the text editor of ubuntu
> > Checklist:
> > 
> > * [x]   My code follows the guidelines of this project.
> > * [x]   I have performed a self-review of my own code.
> > * [x]   I have commented on my code, particularly wherever it was hard to understand.
> > * [x]   I have made corresponding changes to the documentation.
> > * [x]   My changes generate no new warnings.
> > * [x]   I have added test cases that prove my fix is effective or that my feature works.
> 
> Just tick mark the boxes which suits your pull request in order to follow the template and so that we can review accordingly

now see I did some changes. I guess what all I ticked suits my pull request.

**Review by prathimacode-hub — APPROVED** [review]
Amazing work done. PR approved. Very well done. It was a wonderful choice of the script. 👏🤩@dhruv-varshney

**Comment by dhruv-varshney** [comment]
> Amazing work done. PR approved. Very well done. It was a wonderful choice of the script. 👏🤩@dhruv-varshney

Thank you @prathimacode-hub

**Comment by prathimacode-hub** [comment]
Kindly fill the form with your PR link. You have 1 PR merged in this project. Your response hasn't turned up yet. Form is available in slack project channel. @dhruv-varshney

**Comment by dhruv-varshney** [comment]
ok ma'am , i will do it now only . Thanks for telling

**Comment by dhruv-varshney** [comment]
Hello @prathimacode-hub . I filled so many forms that are there in the slack channel but i can not able to get the link of the form where i have to fill the PR link. If possible Kindly send me the link here.

**Comment by prathimacode-hub** [comment]
Ok, sure here is the link : https://docs.google.com/forms/d/e/1FAIpQLScBzeTg4HA0pIGtP6tHaiVUdPbAm9Y3kMn75GBGXvQVQv6wPA/viewform

As said 1 PR = 1 Filled Form @dhruv-varshney

**Pull request merged**
