### PR TITLE
Affine Cipher

### PR DESCRIPTION
**Pull request by manvitha3579**
## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [X] DevIncept Participant
- [ ] Contributor

Closes: #129

### Description
- Affine cipher is actually the multiplicative cipher combined with the Caesar cipher.
- In the affine cipher program, we will split a single integer into two keys.
- The affine cipher needs two keys:
    - Multiplicative cipher multiplication
    - Caesar cipher addition.

## Type of change

What sort of change have you made:

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

## How Has This Been Tested?

- Downloaded and compiled the file Affine_Ciphere.py
- Input message given that I want encrypt or decrypt.
- Input key given
- Generates two modes
    - Encrypt
    - Decrypt
- Finally obtained encrypted and decrypted test for my input message.

## Changes made
- [x] Added 3-4 points in short description
- [x] Added few more test cases
- [x] Added pathlink to all the outputs

## Checklist

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly whereever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by manvitha3579** [comment]
I hope this is perfect now check this once @prathimacode-hub mam

**Comment by prathimacode-hub** [comment]
You should never close issues or PR form your end. Not everypne would take this positive. Letting you know of the things, don't do this again. And you don't have to create new PR for correcting the changes. You can do up the changes directly in your forked repository and push it back again, it would automatically update the existing PR. @manvitha3579

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :
The project file should be as "affine_cipher.py"
Before the start of the project file "affine_cipher.py", add a short description about affine cipher in comments 
In README.md add 2-3 test cases for affine cipher to get more clarity on the topic. 

Kindly do these changes. Don't create new PR again, instead do the changes directly in your forked repo and push it back nothing else needed other than this. Don't complicate and confuse yourself. Any queries, feel free to ask. @manvitha3579

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Yayy. Great start. Congrats on your first PR. Welcome to the repo officially. One of the finest PR here. Amazing work done. ✨🎉👏@manvitha3579

**Pull request merged**
