### PR TITLE
Caesar_Cipher

### PR DESCRIPTION
**Pull request by photon149**
- Info about the related issue 

- [x] DevIncept Participant 
- [ ] Contributor

Closes: #41  number that will be closed through this PR

### Describe the changes you've made

The aim was to Caesar_Cipher problem. The code is running and is working perfectly.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Manually Run  and Tested

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure given. It's not in right format. @photon149

**Comment by photon149** [comment]
Please Review once. I have made some changes.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
I said you to follow the project structure as well.
Changes to be done:
The project folder should be titled as "Caesar Cipher"
The project file should be as "caesar_cipher.py"
The images should be in "Images" folder
The readme files should be as "README.md"
README needs more elaboration. 

Kindly do these changes. @photon149

**Review by prathimacode-hub — APPROVED** [review]
Hey, congrats on your first PR. Yayy. It's approved. Well done. Amazing start. Get going. Welcome to the repo officially.✨🎉👏@photon149

**Pull request merged**
