### PR TITLE
Depth-first Search (DFS) Python

### PR DESCRIPTION
**Pull request by Iamtripathisatyam**
## Issues name: Depth First Search Python, Directory: Graph

- [X] Hacktoberfest2022 Participant 
- [X] Contributor

Closes: #issue number that will be closed through this PR

## Description :
Created a Python script for Depth-first search (DFS), which is basically a technique to traverse nodes in a graph and find the depth.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
This script or code has been tested using various test cases and scenarios.
## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented on my code, particularly wherever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Keep your project name as "Depth First Search" and readme file as "README.md"
Also include the screenshot of the output compiled in "Images" folder.

Kindly do these changes. @Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
> Changes to be done :
> 
> Keep your project name as "Depth First Search" and readme file as "README.md" Also include the screenshot of the output compiled in "Images" folder.
> 
> Kindly do these changes. @Iamtripathisatyam

Done, Please check.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good to see you here once again. 🎉🙌@Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
> PR approved. Good to see you here once again. 🎉🙌@Iamtripathisatyam

Thank you so much, mam.

**Pull request merged**
