### PR TITLE
Added Shell Sort

### PR DESCRIPTION
**Pull request by thejaswin123**
## Related Issue 

- Added Shell sort program in python

- [x] DevIncept Participant 
- [x] Contributor

Closes: #71 

### Describe the changes you've made

Have added a shell sort program with time complexity O(N^2) to sort the list of numbers.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

The program has been run multiple times and checked with different test cases.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add appropriate comments in code to get good understanding of the project. And also add a description aboout your project at the start of the project file and 2-3 test cases at the end of the project file. @thejaswin123

**Comment by thejaswin123** [comment]
> Add appropriate comments in code to get good understanding of the project. And also add a description aboout your project at the start of the project file and 2-3 test cases at the end of the project file. @thejaswin123

Done

**Review by prathimacode-hub — APPROVED** [review]
You are rocking with your PR's, good to see your enthusiasm. Great going. 👌🙌@thejaswin123

**Comment by thejaswin123** [comment]
> You are rocking with your PR's, good to see your enthusiasm. Great going. 👌🙌@thejaswin123

Thank you!!

**Pull request merged**
