### PR TITLE
Face Recognition 

### PR DESCRIPTION
**Pull request by SANJAY-NT**
## Related Issue   #115

- Info about the related issue  

- [x] DevIncept Participant 
- [x] Contributor

Closes: #115 

### Describe the changes you've made

Developed a Face recognition and record application using OpenCV

## Type of change

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] This change requires a documentation update

## How Has This Been Tested?
Describe how have you verified the changes made
  The programs were run on a pycharm IDE on localhost multiple time and checked for issues and error.

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly where ever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.

Note: Project Name is Face_Recognition<br>
         - Script Name ia Face_recognition1.py as the module imported as same name Face_recognition.py it causes conflict hence small change in file.

### CODE REVIEW

**Review by SANJAY-NT — COMMENTED** [review]
Review @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the project structure given. @SANJAY-NT

**Comment by SANJAY-NT** [comment]
I have followed the structure. 
project name file name same.
script name cant be same as it causes py recognition error. 
output file.
requirements.txt

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

The project folder should be titled as "Face Recognition" in /Computer Vision
According to your project there should be in total 3 subfolders inside "Face Recognition"
"Model", "Dataset" and "Images"
The "Model folder should have project file and README file
The project file in "Model" folder should be titled as "face_recognition.py"
In README.md, add usage, use cases, libraries used and conclusion derived from this project after workflow section.
All the .csv files and training images should be in "Dataset" folder
All the output screenshots and related images should be in "Images" folder

This is the project structure. Correct me if I mentioned anything wrong. Kindly do these changes needed. @SANJAY-NT

**Comment by SANJAY-NT** [comment]
There is no dataset as its a pretrained model, only training Images. Except this I shall change all file and add them in structure and commit changes.
@prathimacode-hub

**Comment by prathimacode-hub** [comment]
> There is no dataset as its a pretrained model, only training Images. Except this I shall change all file and add them in structure and commit changes.
> @prathimacode-hub

Yes, that's why I referred clearly that .csv and training images should be in "Dataset". These are nothing but dataset. @SANJAY-NT

**Review by prathimacode-hub — APPROVED** [review]
Whooa, your PR is approved. Great going. Keep up the amazing work and dedication you put up for the issues is mindblowing. Keeo shining. 👌👌@SANJAY-NT

**Pull request merged**
