### PR TITLE
Adding Linear Algebra operations in Python

### PR DESCRIPTION
**Pull request by thebhavana**
## Contribute to this repo

Adding Linear Algebra Operations  

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

Closes: #3 

### Describe the changes you've made

Added Algebric operations in Python using numpy module.

## Type of change

I have added algebric operations as change in initial file. 

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

It has been tested on Visual Studio Code and Jupyter.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Add the PR template given along with issue number. @thebhavana

**Comment by thebhavana** [comment]
> Add the PR template given along with issue number. @thebhavana

Done @prathimacode-hub

**Comment by thebhavana** [comment]
> Add the PR template given along with issue number. @thebhavana

I have added the PR template along with issue number.
Kindly review @`prathimacode-hub`

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Great work. 👏🙌@thebhavana

**Pull request merged**
