### PR TITLE
Lowest common ancestor in binary search tree

### PR DESCRIPTION
**Pull request by pushpit-J19**
## Related Issue 

- Info about the related issue 

- [x] DevIncept Participant 
- [ ] Contributor

Closes: #100 

### Describe the changes you've made

Added the code for finding lowest common ancestor in a binary search tree. Added readme files and the outputs with some examples. Also added good explanation of the concept and the project, and the code is well commented

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manually run and tested

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Hey, issue is already done and merged. You had already created PR earlier. Check it here. 

https://github.com/prathimacode-hub/PyAlgo-Tree/pull/99

**Comment by pushpit-J19** [comment]
> Hey, issue is already done and merged. You had already created PR earlier. Check it here.
> 
> #99 @pushpit-J19

Hi! No this is different. #99 is binary tree lca (an O(n) concept) , this is a BST LCA (an O(log(n) concept)
check again, the concepts are pretty different

**Review by prathimacode-hub — APPROVED** [review]
PR is approved. Oops, sorry I didn't checked on completely, I just saw the title earlier. Fab work. As usual, stunning. 🤩🙌 @pushpit-J19

**Comment by pushpit-J19** [comment]
np. Thx.

**Pull request merged**
