### PR TITLE
BST added

### PR DESCRIPTION
**Pull request by neha030**
**Related Issue**

**Info about the related issue**
Different operations related to binary search tree added 

✅DevIncept Participant

Contributor

Closes: #11 

**Describe the changes you've made**
Added program code in Python for operations on Binary Search Tree

Type of change
**What sort of change have you made:**

 Bug fix (non-breaking change which fixes an issue)
✅ New feature (non-breaking change which adds functionality)
 Code style update (formatting, local variables)
 Breaking change (fix or feature that would cause existing functionality to not work as expected)
 This change requires a documentation update
 How Has This Been Tested?
 Code is run multiple times with different inputs and test cases and output is verified.

 **Checklist:**
 My code follows the guidelines of this project.
✅ I have performed a self-review of my own code.
✅ I have commented on my code, particularly wherever it was hard to understand.
✅ I have made corresponding changes to the documentation.
✅ My changes generate no new warnings.
✅ I have added test cases that prove my fix is effective or that my feature works.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Imaes should be in "Images" folder.
Add compilation steps in "README.md"

Kindly do these changes. @neha030

**Comment by neha030** [comment]
> Imaes should be in "Images" folder.
> Add compilation steps in "README.md"
> 
> Kindly do these changes. @neha030

Ok i will make the necessary changes

**Comment by neha030** [comment]
I have done the changes please review

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Images should be in "Images" folder. @neha030

**Comment by neha030** [comment]
> Images should be in "Images" folder. @neha030

but the images are in the images folder itself , Should I change it from "images" to "Images"

**Comment by prathimacode-hub** [comment]
> > Images should be in "Images" folder. @neha030
> 
> but the images are in the images folder itself , Should I change it from "images" to "Images"

Yes

**Comment by neha030** [comment]
Edit file option is only enabled to change the python and readme file , its disabled for images 
Please help me how can i do the changes
and even when tried using git bash it's showing nothing to commit even after renaming the file 
Please help

**Comment by prathimacode-hub** [comment]
Go to your forked repo, Add images using 'Add files' option and push it again.

**Comment by neha030** [comment]
> Go to your forked repo, Add images using 'Add files' option and push it again. @neha030

Thank You for helping 😊

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Why did you add in separate images folder
I told images should be in "Images" folder that's inside Binary Search Tree. I told to correct the case-sensitive letters. Not adding extra images folder in project repo. 
Also change the link of images you added up after "Images" folder is created with 5 output images, present inside "Binary Search Tree" folder.
The image links should not be user-images content it should be the file path.

@neha030

**Comment by prathimacode-hub** [comment]
Kindly do the requested changes. @neha030

**Comment by neha030** [comment]
I have done all changes but not able to convert 'i' to 'I'

**Comment by photon149** [comment]
@neha030  I faced a similar problem as well earlier .You should try deleting the whole images folder . Then create a new folder named "Images" ,then again upload all the images in that subfolder. Also , do all these changes in your forked repo. 
I hope it helps.

**Comment by prathimacode-hub** [comment]
> @neha030 I faced a similar problem as well earlier .You should try deleting the whole images folder ( there is a delete directory option to remove a folder) . Then create a new folder named "Images" ,then again upload all the images in that subfolder. Also , do all these changes in your forked repo they will reflect in your pull request.
> I hope it helps.

Thanks for helping neha out. @photon149. @neha030, follow these steps said.

**Comment by neha030** [comment]
I think I have done all the changes now
Thank you @photon149 for guidance 
@prathimacode-hub Please review

**Review by prathimacode-hub — APPROVED** [review]
Exclusive work and wonderful way of presenting your project. Congrats on your first PR. Welcome to repo officially. Yayy. This was an amazing kickstart from you. Keep it up. ✨🎉👏 @neha030

**Pull request merged**
