### PR TITLE
Added bubble sort in sorting folder.

### PR DESCRIPTION
**Pull request by siddhi-244**
## Related Issue 

- Add Bubble sort.

- [x] DevIncept Participant 
- [ ] Contributor

Closes: #9 

### Describe the changes you've made
I have added bubble sort algorithm. 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made
I ran the program in my laptop as well as online ide.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added test cases that prove my fix is effective or that my feature works.

 
Screenshot_20210710-181018_Chrome

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
It's not this way. Create a project folder as "Bubble Sort"
Then add bubble_sort.py and README.md file. The README template is provided. It should be brief enough. Also add appropriate images needed to explain it better
Also since it's a .py file, output screenshot is must. Add the screenshot of the compilation taken and place it in "Images" folder. All images should be present here.

Kindly do these needful changes. @siddhi-244

**Comment by siddhi-244** [comment]
> Changes to be done:
> It's not this way. Create a project folder as "Bubble Sort"
> Then add bubble_sort.py and README.md file. The README template is provided. It should be brief enough. Also add appropriate images needed to explain it better
> Also since it's a .py file, output screenshot is must. Add the screenshot of the compilation taken and place it in "Images" folder. All images should be present here.
> 
> Kindly do these needful changes. @siddhi-244

Sure !

**Comment by siddhi-244** [comment]
@prathimacode-hub  I have done the changes. Please check!

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The project folder should be as "Bubble Sort"
And also the image link in README.md file is in 'user-images' content, instead it should be the file path of the image present in this repository. 
Add the images in "Images" folder.
In 'README.md' add up a command of how compilation is done.

Other than that, all good. Kindly do these changes. @siddhi-244

**Review by prathimacode-hub — APPROVED** [review]
Yayy, your PR is merged. Good start. Welcome to the repo officially. Congrats. ✨🎉@siddhi-244

**Comment by prathimacode-hub** [comment]
Kindly fill the form with your PR link. Your response hasn't turned up yet. Your have 4 PR's merged in total in this project. Form is available in slack project channel. @siddhi-244

**Comment by siddhi-244** [comment]
> Kindly fill the form with your PR link. Your response hasn't turned up yet. Your have 4 PR's merged in total in this project. Form is available in slack project channel. @siddhi-244

Maam can uh please check once again I have filled the form!

**Comment by prathimacode-hub** [comment]
Yes, got 4 responses. great. Cool.

**Pull request merged**
